//! Golden parity test for Task T4 (candle entity-transformer inference,
//! docs/superpowers/plans/2026-07-16-entity-transformer-obs-v1.md). Loads
//! `tests/fixtures/policy_v1_golden.npz` (generated by
//! `scripts/gen_policy_v1_fixture.py` from the T5 Python net,
//! `python/construct/learn/model_v1.py`), builds `policy_v1::EntityPolicy`
//! from the fixture's state_dict arrays, forwards the fixture's random batch
//! and asserts the candle output matches PyTorch's within 1e-4.

use construct_engine::policy_v1::EntityPolicy;
use ndarray::ArrayD;
use ndarray_npy::NpzReader;
use std::collections::HashMap;
use std::fs::File;

fn npz() -> NpzReader<File> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/policy_v1_golden.npz");
    let file = File::open(path)
        .unwrap_or_else(|e| panic!("run scripts/gen_policy_v1_fixture.py first: {path}: {e}"));
    NpzReader::new(file).expect("valid npz")
}

fn read_f32(npz: &mut NpzReader<File>, name: &str) -> (Vec<f32>, Vec<usize>) {
    let arr: ArrayD<f32> = npz.by_name(name).unwrap_or_else(|e| panic!("reading {name}: {e}"));
    let shape = arr.shape().to_vec();
    let data: Vec<f32> = arr.iter().copied().collect();
    (data, shape)
}

fn read_i64(npz: &mut NpzReader<File>, name: &str) -> Vec<i64> {
    let arr: ArrayD<i64> = npz.by_name(name).unwrap_or_else(|e| panic!("reading {name}: {e}"));
    arr.iter().copied().collect()
}

#[test]
fn candle_forward_matches_pytorch_golden() {
    let mut npz = npz();
    let names = npz.names().unwrap();

    // Non-weight arrays saved alongside the state_dict.
    let io_keys = [
        "ents", "mask", "query", "prev", "expected_logits", "expected_value", "dims",
    ];

    let mut weights: HashMap<String, (Vec<f32>, Vec<usize>)> = HashMap::new();
    for name in &names {
        if io_keys.contains(&name.as_str()) {
            continue;
        }
        weights.insert(name.clone(), read_f32(&mut npz, name));
    }

    let (ents, ents_shape) = read_f32(&mut npz, "ents");
    let (mask_f, mask_shape) = read_f32(&mut npz, "mask");
    let (query, _query_shape) = read_f32(&mut npz, "query");
    let prev = read_i64(&mut npz, "prev");
    let (expected_logits, _) = read_f32(&mut npz, "expected_logits");
    let (expected_value, _) = read_f32(&mut npz, "expected_value");
    let dims = read_i64(&mut npz, "dims"); // [d_model, layers, heads, ff, B]

    let b = ents_shape[0];
    assert_eq!(b, dims[4] as usize);
    assert_eq!(mask_shape[0], b);
    let mask: Vec<bool> = mask_f.iter().map(|&v| v != 0.0).collect();

    let heads = dims[2] as usize;
    let policy = EntityPolicy::new(&weights, heads).expect("EntityPolicy::new");

    let (logits, values) = policy
        .forward(&ents, &mask, &query, &prev, b)
        .expect("forward");

    assert_eq!(logits.len(), expected_logits.len());
    assert_eq!(values.len(), expected_value.len());

    let max_l = logits
        .iter()
        .zip(&expected_logits)
        .map(|(a, b)| (a - b).abs())
        .fold(0f32, f32::max);
    let max_v = values
        .iter()
        .zip(&expected_value)
        .map(|(a, b)| (a - b).abs())
        .fold(0f32, f32::max);

    assert!(max_l < 1e-4, "logits max abs diff {max_l}");
    assert!(max_v < 1e-4, "values max abs diff {max_v}");
}
