"""Golden fixtures for the Rust Necto obs builder, generated by driving the REAL
NectoObsBuilder from deploy/external/necto/necto_obs.py.

This exists because Necto's observation is NOT Nexto's despite identical q32/kv24
widths (ball-first entities, pos+vel relative with no heading rotation, blue-keyed
team flags, stateful timers in column 21). A re-derivation was what produced a
bot driving on nonsense and a bogus 96-0 benchmark -- so the reference here is the
bot's own code, with rlgym_compat / rlbot stubbed out.

Necto's timers are STATEFUL, so each case is a SEQUENCE of frames: the fixture
records every frame's (q, kv) and the Rust test replays the same sequence through
one NectoTimers instance.
"""
import json
import pathlib
import sys
import types

import numpy as np

BOOST_LOCATIONS = [
    [0.0, -4240.0, 70.0], [-1792.0, -4184.0, 70.0], [1792.0, -4184.0, 70.0],
    [-3072.0, -4096.0, 73.0], [3072.0, -4096.0, 73.0], [-940.0, -3308.0, 70.0],
    [940.0, -3308.0, 70.0], [0.0, -2816.0, 70.0], [-3584.0, -2484.0, 70.0],
    [3584.0, -2484.0, 70.0], [-1788.0, -2300.0, 70.0], [1788.0, -2300.0, 70.0],
    [-2048.0, -1036.0, 70.0], [0.0, -1024.0, 70.0], [2048.0, -1036.0, 70.0],
    [-3584.0, 0.0, 73.0], [-1024.0, 0.0, 70.0], [1024.0, 0.0, 70.0],
    [3584.0, 0.0, 73.0], [-2048.0, 1036.0, 70.0], [0.0, 1024.0, 70.0],
    [2048.0, 1036.0, 70.0], [-1788.0, 2300.0, 70.0], [1788.0, 2300.0, 70.0],
    [-3584.0, 2484.0, 70.0], [3584.0, 2484.0, 70.0], [0.0, 2816.0, 70.0],
    [-940.0, 3310.0, 70.0], [940.0, 3308.0, 70.0], [-3072.0, 4096.0, 73.0],
    [3072.0, 4096.0, 73.0], [-1792.0, 4184.0, 70.0], [1792.0, 4184.0, 70.0],
    [0.0, 4240.0, 70.0],
]


def _stub():
    rc = types.ModuleType("rlgym_compat")
    rc.BLUE_TEAM, rc.ORANGE_TEAM = 0, 1
    class _S: pass
    rc.V1GameState = _S
    rc.V1PlayerData = _S
    sys.modules.setdefault("rlgym_compat", rc)
    rb = types.ModuleType("rlbot")
    flat = types.ModuleType("rlbot.flat")
    flat.FieldInfo = _S
    rb.flat = flat
    sys.modules.setdefault("rlbot", rb)
    sys.modules.setdefault("rlbot.flat", flat)


def load_builder():
    _stub()
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        "necto_obs", "deploy/external/necto/necto_obs.py")
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


class Loc:
    def __init__(self, v): self.x, self.y, self.z = v


class Pad:
    def __init__(self, v): self.location, self.is_full_boost = Loc(v), v[2] > 72


class FieldInfo:
    def __init__(self): self.boost_pads = [Pad(v) for v in BOOST_LOCATIONS]


class CarData:
    def __init__(self, pos, vel, ang, fw, up):
        self.position = np.array(pos); self.linear_velocity = np.array(vel)
        self.angular_velocity = np.array(ang)
        self._fw = np.array(fw); self._up = np.array(up)
    def forward(self): return self._fw
    def up(self): return self._up


class Player:
    def __init__(self, cid, team, cd, boost, on_ground, has_flip):
        self.car_id, self.team_num, self.car_data = cid, team, cd
        self.boost_amount, self.on_ground, self.has_flip = boost, on_ground, has_flip


class Ball:
    def __init__(self, pos, vel, ang):
        self.position = np.array(pos); self.linear_velocity = np.array(vel)
        self.angular_velocity = np.array(ang)


class State:
    def __init__(self, players, ball, pads):
        self.players, self.ball, self.boost_pads = players, ball, pads


def rnd_car(rng, cid, team):
    on_ground = bool(rng.random() > 0.5)
    return dict(
        cid=cid, team=team,
        pos=rng.uniform(-4000, 4000, 3).tolist(),
        vel=rng.uniform(-2000, 2000, 3).tolist(),
        ang=rng.uniform(-5, 5, 3).tolist(),
        fw=rng.uniform(-1, 1, 3).tolist(),
        up=rng.uniform(-1, 1, 3).tolist(),
        boost=float(rng.uniform(0, 1)),
        on_ground=on_ground,
        # engine derives has_flip_or_jump() = on_ground || (...), so an
        # (on_ground, not has_flip) state is unreachable
        has_flip=True if on_ground else bool(rng.random() > 0.5),
    )


def main():
    m = load_builder()
    rng = np.random.default_rng(7)
    sequences = []
    for _ in range(4):
        # demo_timers is a CLASS attribute (shared across instances), so a fresh
        # builder does not reset it. In deploy there is one builder per process,
        # so clear it per sequence to model a fresh match.
        from collections import Counter
        m.NectoObsBuilder.demo_timers = Counter()
        builder = m.NectoObsBuilder(FieldInfo())
        frames = []
        for _ in range(6):                       # timers are stateful -> a sequence
            cars = [rnd_car(rng, 0, 0), rnd_car(rng, 1, 1)]
            pads = (rng.random(34) > 0.5).astype(np.float64)
            ball = dict(pos=rng.uniform(-4000, 4000, 3).tolist(),
                        vel=rng.uniform(-2000, 2000, 3).tolist(),
                        ang=rng.uniform(-5, 5, 3).tolist())
            players = [Player(c["cid"], c["team"],
                              CarData(c["pos"], c["vel"], c["ang"], c["fw"], c["up"]),
                              c["boost"], c["on_ground"], c["has_flip"]) for c in cars]
            st = State(players, Ball(ball["pos"], ball["vel"], ball["ang"]), pads)
            prev = rng.uniform(-1, 1, 8)
            # ONE viewer per frame (the orange car), matching how the engine drives
            # a foreign opponent: exactly one decision per arena per step.
            q, kv, mask = builder.build_obs(players[1], st, prev)
            frames.append({
                "cars": cars, "pads": pads.tolist(), "ball": ball,
                "prev_action": prev.tolist(), "self_idx": 1,
                "q": np.asarray(q).reshape(-1).tolist(),
                "kv": np.asarray(kv)[0].tolist(),
                "mask": np.asarray(mask).reshape(-1).tolist(),
            })
        sequences.append(frames)

    out = pathlib.Path("engine/tests/fixtures/necto_obs.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"sequences": sequences}))
    k0 = np.asarray(sequences[0][0]["kv"])
    print(f"wrote {out}: {len(sequences)} sequences x {len(sequences[0])} frames, "
          f"q={len(sequences[0][0]['q'])}, kv={k0.shape}")


if __name__ == "__main__":
    main()
