"""Golden fixture for the Rust Element net, generated by driving the REAL
Element Agent from RLMarlbot (rlmarlbot/element/agent.py).

Element's agent.py has no relative imports, so it loads directly with importlib;
Agent.__init__ reads model.p from its own directory. Weights are unlicensed and
never committed -- only the (obs -> action) pairs land in the fixture.

Usage: gen_element_fixture.py <RLMarlbot>/rlmarlbot/element
"""
import importlib.util
import json
import pathlib
import sys

import numpy as np

ACTION_TRANS = np.array([-1, -1, -1, -1, -1, 0, 0, 0])


def main():
    src = pathlib.Path(sys.argv[1])
    spec = importlib.util.spec_from_file_location("element_agent", src / "agent.py")
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)

    obs_size = 107          # CustomObs(cars=2)
    agent = m.Agent(obs_size, action_categoricals=5, action_bernoullis=3)

    rng = np.random.default_rng(11)
    cases = []
    for _ in range(24):
        obs = rng.standard_normal(obs_size).astype(np.float32)
        action = agent.act(obs)[0] + ACTION_TRANS
        cases.append({"obs": obs.tolist(), "action": [float(x) for x in action]})

    out = pathlib.Path("engine/tests/fixtures/element_net.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"obs_size": obs_size, "cases": cases}))
    print(f"wrote {out}: {len(cases)} cases, obs={obs_size}")


if __name__ == "__main__":
    main()
