//! Nexto/Necto's `NextoObsBuilder` entity observation, built from the engine
//! GameState. Reproduces deploy/external/nexto/nexto_obs.py byte-exact -- see
//! nexto_obs_test.rs, whose fixture is generated by driving the REAL Python
//! builder (not a re-derivation).
//!
//! Shape: a query row `q` of 32 floats (the self entity's own 24 features plus
//! the 8-float previous action) and `kv`, one 24-float row per entity, where
//! entities are `players ++ [ball] ++ 34 boost pads`. The mask marks padding
//! entities; with a full complement it is all false.
//!
//! Two transforms are easy to get wrong and are the reason this is golden-tested:
//!   * ORANGE inversion multiplies every vector triple's x,y by -1 (`_invert`)
//!     AND swaps the IS_MATE / IS_OPP flags.
//!   * `convert_to_relative` subtracts the self position from every entity's
//!     position and then ROTATES the x,y of all five vector triples (pos, lin
//!     vel, forward, up, ang vel) into the self's heading,
//!     `theta = atan2(fw.x, fw.y)`.
//!
//! Normalisers differ from Immortal's AdvancedObs: ang vel is /5.5 here, not /PI.
use crate::obs_advanced::{rlgym_to_canon, BOOST_LOCATIONS};
use rocketsim_rs::sim::Team;
use rocketsim_rs::GameState;

pub const NEXTO_Q: usize = 32;
pub const NEXTO_KV: usize = 24;
pub const NEXTO_PADS: usize = 34;

// kv feature indices (nexto_obs.py)
const IS_SELF: usize = 0;
const IS_MATE: usize = 1;
const IS_OPP: usize = 2;
const IS_BALL: usize = 3;
const IS_BOOST: usize = 4;
const POS: usize = 5;
const LIN_VEL: usize = 8;
const FW: usize = 11;
const UP: usize = 14;
const ANG_VEL: usize = 17;
const BOOST: usize = 20;
const DEMO: usize = 21;
const ON_GROUND: usize = 22;
const HAS_FLIP: usize = 23;

/// `_norm = [1]*5 + [2300]*6 + [1]*6 + [5.5]*3 + [1]*4`
#[inline]
fn norm_at(i: usize) -> f32 {
    match i {
        0..=4 => 1.0,
        5..=10 => 2300.0,
        11..=16 => 1.0,
        17..=19 => 5.5,
        _ => 1.0,
    }
}

/// `_invert = [1]*5 + [-1, -1, 1]*5 + [1]*4` -- flip x,y of each vector triple.
#[inline]
fn invert_at(i: usize) -> f32 {
    if !(POS..BOOST).contains(&i) {
        return 1.0;
    }
    match (i - POS) % 3 {
        0 | 1 => -1.0,
        _ => 1.0,
    }
}

/// Number of entity rows for `n_players`: players, one ball, 34 pads.
pub fn n_entities(n_players: usize) -> usize {
    n_players + 1 + NEXTO_PADS
}

/// Build the (q, kv, mask) observation for `state.cars[car_idx]`.
///
/// `q` must be `NEXTO_Q`, `kv` must be `n_entities(n) * NEXTO_KV`, and `mask`
/// `n_entities(n)` long. Players are ordered by ascending car id, matching
/// rlgym_compat (`players.sort(key=car_id)`).
pub fn build_nexto_obs(
    state: &GameState,
    car_idx: usize,
    prev_action: &[f32; 8],
    q: &mut [f32],
    kv: &mut [f32],
    mask: &mut [bool],
) {
    let n_players = state.cars.len();
    let n_ent = n_entities(n_players);
    assert_eq!(q.len(), NEXTO_Q);
    assert_eq!(kv.len(), n_ent * NEXTO_KV);
    assert_eq!(mask.len(), n_ent);
    kv.fill(0.0);
    q.fill(0.0);
    mask.fill(false);

    // rlgym_compat sorts players by car id; our GameState does not.
    let mut order: Vec<usize> = (0..n_players).collect();
    order.sort_by_key(|&i| state.cars[i].id);
    let self_row = order.iter().position(|&i| i == car_idx).expect("car in state");
    let orange = state.cars[car_idx].team == Team::Orange;

    // --- players ---
    for (row, &ci) in order.iter().enumerate() {
        let c = &state.cars[ci];
        let s = &c.state;
        let o = row * NEXTO_KV;
        let team = if c.team == Team::Orange { 1.0 } else { 0.0 };
        kv[o + IS_MATE] = 1.0 - team;
        kv[o + IS_OPP] = team;
        if row == self_row {
            kv[o + IS_SELF] = 1.0;
        }
        kv[o + POS] = s.pos.x;
        kv[o + POS + 1] = s.pos.y;
        kv[o + POS + 2] = s.pos.z;
        kv[o + LIN_VEL] = s.vel.x;
        kv[o + LIN_VEL + 1] = s.vel.y;
        kv[o + LIN_VEL + 2] = s.vel.z;
        kv[o + FW] = s.rot_mat.forward.x;
        kv[o + FW + 1] = s.rot_mat.forward.y;
        kv[o + FW + 2] = s.rot_mat.forward.z;
        kv[o + UP] = s.rot_mat.up.x;
        kv[o + UP + 1] = s.rot_mat.up.y;
        kv[o + UP + 2] = s.rot_mat.up.z;
        kv[o + ANG_VEL] = s.ang_vel.x;
        kv[o + ANG_VEL + 1] = s.ang_vel.y;
        kv[o + ANG_VEL + 2] = s.ang_vel.z;
        // rlgym encodes boost as a fraction in [0,1]; the engine stores 0..100.
        kv[o + BOOST] = s.boost / 100.0;
        kv[o + DEMO] = s.is_demoed as u8 as f32;
        kv[o + ON_GROUND] = s.is_on_ground as u8 as f32;
        kv[o + HAS_FLIP] = s.has_flip_or_jump() as u8 as f32;
    }

    // --- ball ---
    {
        let o = n_players * NEXTO_KV;
        let b = &state.ball;
        kv[o + IS_BALL] = 1.0;
        kv[o + POS] = b.pos.x;
        kv[o + POS + 1] = b.pos.y;
        kv[o + POS + 2] = b.pos.z;
        kv[o + LIN_VEL] = b.vel.x;
        kv[o + LIN_VEL + 1] = b.vel.y;
        kv[o + LIN_VEL + 2] = b.vel.z;
        kv[o + ANG_VEL] = b.ang_vel.x;
        kv[o + ANG_VEL + 1] = b.ang_vel.y;
        kv[o + ANG_VEL + 2] = b.ang_vel.z;
    }

    // --- boost pads (rlgym BOOST_LOCATIONS order) ---
    {
        let perm = rlgym_to_canon(&state.pads);
        for j in 0..NEXTO_PADS {
            let o = (n_players + 1 + j) * NEXTO_KV;
            let loc = BOOST_LOCATIONS[j];
            kv[o + IS_BOOST] = 1.0;
            kv[o + POS] = loc[0];
            kv[o + POS + 1] = loc[1];
            kv[o + POS + 2] = loc[2];
            // 0.12 + 0.88 * is_big  (big pads sit above z = 72)
            kv[o + BOOST] = 0.12 + 0.88 * ((loc[2] > 72.0) as u8 as f32);
            kv[o + DEMO] = state.pads[perm[j]].state.is_active as u8 as f32;
        }
    }

    // --- orange inversion + team-flag swap ---
    if orange {
        for row in 0..n_ent {
            let o = row * NEXTO_KV;
            for i in 0..NEXTO_KV {
                kv[o + i] *= invert_at(i);
            }
            kv.swap(o + IS_MATE, o + IS_OPP);
        }
    }

    // --- normalise ---
    for row in 0..n_ent {
        let o = row * NEXTO_KV;
        for i in 0..NEXTO_KV {
            kv[o + i] /= norm_at(i);
        }
    }

    // --- query = self row (absolute) ++ previous action ---
    let so = self_row * NEXTO_KV;
    q[..NEXTO_KV].copy_from_slice(&kv[so..so + NEXTO_KV]);
    q[NEXTO_KV..NEXTO_Q].copy_from_slice(prev_action);

    // --- convert_to_relative: translate then rotate into the self heading ---
    let (qx, qy, qz) = (q[POS], q[POS + 1], q[POS + 2]);
    let theta = q[FW].atan2(q[FW + 1]);
    let (st, ct) = theta.sin_cos();
    for row in 0..n_ent {
        let o = row * NEXTO_KV;
        kv[o + POS] -= qx;
        kv[o + POS + 1] -= qy;
        kv[o + POS + 2] -= qz;
        for i in (POS..ANG_VEL + 3).step_by(3) {
            let (x, y) = (kv[o + i], kv[o + i + 1]);
            kv[o + i] = ct * x - st * y;
            kv[o + i + 1] = st * x + ct * y;
        }
    }

    // --- mask: only padding entities are masked; a full complement masks none ---
}
